#!/bin/bash
# extract.sh — Extract all LowPLC F* modules to C via KaRaMeL
#
# Usage: cd fstar/src && bash ../extract.sh
set -e

FSTAR_EXE=/home/iamfo470/phd/everparse/opt/FStar/out/bin/fstar.exe
KRML_HOME=/home/iamfo470/phd/everparse/opt/karamel
Z3_PATH=/home/iamfo470/phd/everparse/opt/z3/z3-4.13.3
BUILD_DIR=../build

FSTAR_COMMON="$FSTAR_EXE --smt $Z3_PATH"
FSTAR_IMPL="$FSTAR_COMMON --include $KRML_HOME/krmllib --include $KRML_HOME/krmllib/obj"
KRML_COMMON="$KRML_HOME/krml -fstar $FSTAR_EXE -fsopt --smt -fsopt $Z3_PATH \
  -tmpdir $BUILD_DIR -skip-compilation -skip-linking -minimal \
  -drop FStar.*,LowStar.*,Prims -warn-error -2"

# All FB modules: spec_file impl_file module_prefix [extra_fstar_opts]
# Bistables (no extra deps beyond their own spec)
BISTABLE_FBS="SR RS"
# Edge detectors
EDGE_FBS="R_TRIG F_TRIG"
# Counters (use Int16)
COUNTER_FBS="CTU CTD CTUD"
# Timers (use UInt32 ticks)
TIMER_FBS="TON TOF TP"

echo "================================================================"
echo "  LowPLC — Verified IEC 61131-3 FB Extraction"
echo "================================================================"
echo ""

# ── Step 1: Verify all spec modules ──
echo "=== Step 1: Verify spec modules ==="
for fb in $BISTABLE_FBS $EDGE_FBS $COUNTER_FBS $TIMER_FBS; do
  echo -n "  LowPLC.$fb.fst ... "
  $FSTAR_COMMON LowPLC.$fb.fst 2>&1 | tail -1
done
echo ""

# ── Step 2: Verify all impl modules ──
echo "=== Step 2: Verify impl modules ==="
for fb in $BISTABLE_FBS $EDGE_FBS $COUNTER_FBS $TIMER_FBS; do
  EXTRA=""
  if [ "$fb" = "CTUD" ] || [ "$fb" = "TP" ]; then
    EXTRA="--z3rlimit 80"
  fi
  echo -n "  LowPLC.$fb.Impl.fst ... "
  $FSTAR_IMPL $EXTRA LowPLC.$fb.Impl.fst 2>&1 | tail -1
done
echo ""

# ── Step 3: KaRaMeL extraction ──
echo "=== Step 3: KaRaMeL extraction ==="

# Clean previous KaRaMeL output (keep shim header)
rm -f "$BUILD_DIR"/LowPLC_*.c "$BUILD_DIR"/LowPLC_*.h "$BUILD_DIR"/LowPLC_*.o
rm -f "$BUILD_DIR"/Makefile.basic "$BUILD_DIR"/Makefile.include "$BUILD_DIR"/out.krml

for fb in $BISTABLE_FBS $EDGE_FBS $COUNTER_FBS $TIMER_FBS; do
  echo -n "  LowPLC.$fb.Impl → C ... "
  $KRML_COMMON \
    -no-prefix LowPLC.$fb.Impl \
    -bundle "LowPLC.${fb}.Impl=LowPLC.${fb},LowPLC.${fb}.Impl" \
    LowPLC.$fb.Impl.fst 2>&1 | grep -c "^" | xargs -I{} echo "done ({} lines output)"
done

# Clean KaRaMeL temp files
rm -f "$BUILD_DIR"/Makefile.basic "$BUILD_DIR"/Makefile.include "$BUILD_DIR"/out.krml
echo ""

# ── Step 4: Generate shim header with all tuple accessors ──
echo "=== Step 4: Generate shim header ==="
cat > "$BUILD_DIR/lowplc_krml_shim.h" << 'SHIMEOF'
/**
 * lowplc_krml_shim.h — Minimal KaRaMeL runtime shims for LowPLC
 *
 * Provides the fst/snd tuple accessors and KRML_HOST macros that
 * KaRaMeL-extracted C code references. For bare-metal targets,
 * KRML_HOST_EXIT is a fault loop.
 *
 * AUTO-GENERATED by extract.sh — do not edit manually.
 */
#ifndef LOWPLC_KRML_SHIM_H
#define LOWPLC_KRML_SHIM_H

#include <stdint.h>
#include <stdbool.h>

/* KRML_HOST macros — used in unreachable default branches */
#ifndef KRML_HOST_EPRINTF
  #define KRML_HOST_EPRINTF(...) ((void)0)
#endif

#ifndef KRML_HOST_EXIT
  #ifdef __arm__
    #define KRML_HOST_EXIT(x) do { for(;;); } while(0)
  #else
    #include <stdlib.h>
    #define KRML_HOST_EXIT(x) exit(x)
  #endif
#endif

SHIMEOF

# Scan generated C files for tuple accessor references and generate macros
for cfile in "$BUILD_DIR"/LowPLC_*_Impl.c; do
  [ -f "$cfile" ] || continue
  grep -oE 'FStar_Pervasives_Native_(fst|snd)__[A-Za-z0-9_]+' "$cfile" 2>/dev/null | sort -u | while read -r accessor; do
    kind=$(echo "$accessor" | grep -oE '(fst|snd)')
    echo "#define $accessor(x) ((x).$kind)" >> "$BUILD_DIR/lowplc_krml_shim.h"
  done
done

echo "" >> "$BUILD_DIR/lowplc_krml_shim.h"
echo "#endif /* LOWPLC_KRML_SHIM_H */" >> "$BUILD_DIR/lowplc_krml_shim.h"
echo "  Generated lowplc_krml_shim.h"
echo ""

# ── Step 5: Patch generated files ──
echo "=== Step 5: Patch generated files ==="
# Add stdint/stdbool includes to headers
for hdr in "$BUILD_DIR"/LowPLC_*_Impl.h; do
  if [ -f "$hdr" ] && ! grep -q '#include <stdint.h>' "$hdr"; then
    sed -i '1i #include <stdint.h>\n#include <stdbool.h>' "$hdr"
    echo "  Patched header: $(basename $hdr)"
  fi
done
# Add shim include to .c files (after their own .h include)
for cfile in "$BUILD_DIR"/LowPLC_*_Impl.c; do
  [ -f "$cfile" ] || continue
  if ! grep -q 'lowplc_krml_shim.h' "$cfile"; then
    sed -i '/#include "LowPLC_.*_Impl.h"/a #include "lowplc_krml_shim.h"' "$cfile"
    echo "  Patched source: $(basename $cfile)"
  fi
done
echo ""

# ── Step 6: Cross-compile for Cortex-M7 ──
echo "=== Step 6: Cross-compile for Cortex-M7 ==="
CC=arm-none-eabi-gcc
CFLAGS="-mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard -O2 -g -Wall -Wextra -Wno-unused-parameter"

for cfile in "$BUILD_DIR"/LowPLC_*_Impl.c; do
  [ -f "$cfile" ] || continue
  ofile="${cfile%.c}.o"
  name=$(basename "$cfile")
  echo -n "  $name ... "
  $CC $CFLAGS -c "$cfile" -I "$BUILD_DIR" -o "$ofile"
  echo "ok"
done
echo ""

# ── Results ──
echo "=== Results ==="
echo ""
echo "Extracted C files:"
ls -la "$BUILD_DIR"/LowPLC_*_Impl.c 2>/dev/null | awk '{print "  " $NF " (" $5 " bytes)"}'
echo ""
echo "Cross-compiled objects:"
arm-none-eabi-size "$BUILD_DIR"/LowPLC_*_Impl.o 2>/dev/null
echo ""
echo "All done."
