/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/iamfo470/phd/everparse/opt/karamel/krml -fstar /home/iamfo470/phd/everparse/opt/FStar/out/bin/fstar.exe -skip-compilation -tmpdir build_low -drop FStar.*,LowStar.*,Prims,C.* -warn-error -2 -fsopt --include -fsopt src src/LowPLC.Interp.Low.fst
  F* version: <unknown>
  KaRaMeL version: fb36fecb
 */

#include "LowPLC_Interp_Low.h"

bool LowPLC_Interp_Low_get_bool_low(LowPLC_Interp_Low_low_pool p, uint32_t i)
{
  return p.lp_bools[i];
}

void LowPLC_Interp_Low_set_bool_low(LowPLC_Interp_Low_low_pool p, uint32_t i, bool v)
{
  p.lp_bools[i] = v;
}

int16_t LowPLC_Interp_Low_get_int_low(LowPLC_Interp_Low_low_pool p, uint32_t i)
{
  return p.lp_ints[i];
}

void LowPLC_Interp_Low_set_int_low(LowPLC_Interp_Low_low_pool p, uint32_t i, int16_t v)
{
  p.lp_ints[i] = v;
}

uint16_t LowPLC_Interp_Low_read_u16_le_low(uint8_t *code, uint32_t off)
{
  uint8_t r0 = code[off];
  uint8_t r1 = code[off + 1U];
  uint16_t b0 = (uint16_t)r0;
  uint16_t b1 = (uint16_t)r1;
  return (uint32_t)b0 + (uint32_t)b1 * 256U;
}

uint32_t LowPLC_Interp_Low_read_u32_le_low(uint8_t *code, uint32_t off)
{
  uint8_t r0 = code[off];
  uint8_t r1 = code[off + 1U];
  uint8_t r2 = code[off + 2U];
  uint8_t r3 = code[off + 3U];
  uint32_t b0 = (uint32_t)r0;
  uint32_t b1 = (uint32_t)r1;
  uint32_t b2 = (uint32_t)r2;
  uint32_t b3 = (uint32_t)r3;
  return b0 + b1 * 256U + b2 * 65536U + b3 * 16777216U;
}

int16_t LowPLC_Interp_Low_read_i16_le_low(uint8_t *code, uint32_t off)
{
  uint8_t r0 = code[off];
  uint8_t r1 = code[off + 1U];
  uint16_t lo = (uint16_t)r0;
  uint16_t hi = (uint16_t)r1;
  uint16_t raw = (uint32_t)lo + (uint32_t)hi * 256U;
  return (int16_t)raw;
}

int16_t LowPLC_Interp_Low_wrap_i16_low(int16_t x)
{
  return x;
}

int16_t LowPLC_Interp_Low_add_wrap_low(int16_t a, int16_t b)
{
  return (int16_t)((int32_t)a + (int32_t)b);
}

int16_t LowPLC_Interp_Low_sub_wrap_low(int16_t a, int16_t b)
{
  return (int16_t)((int32_t)a - (int32_t)b);
}

int16_t LowPLC_Interp_Low_mul_wrap_low(int16_t a, int16_t b)
{
  return (int16_t)((int32_t)a * (int32_t)b);
}

uint8_t LowPLC_Interp_Low_tag_load_true_u8 = 0x01U;

uint8_t LowPLC_Interp_Low_tag_load_false_u8 = 0x02U;

uint8_t LowPLC_Interp_Low_tag_load_int_u8 = 0x03U;

uint8_t LowPLC_Interp_Low_tag_bool_not_u8 = 0x10U;

uint8_t LowPLC_Interp_Low_tag_bool_and_u8 = 0x11U;

uint8_t LowPLC_Interp_Low_tag_bool_or_u8 = 0x12U;

uint8_t LowPLC_Interp_Low_tag_bool_xor_u8 = 0x13U;

uint8_t LowPLC_Interp_Low_tag_copy_bool_u8 = 0x14U;

uint8_t LowPLC_Interp_Low_tag_int_add_u8 = 0x20U;

uint8_t LowPLC_Interp_Low_tag_int_sub_u8 = 0x21U;

uint8_t LowPLC_Interp_Low_tag_int_mul_u8 = 0x22U;

uint8_t LowPLC_Interp_Low_tag_copy_int_u8 = 0x23U;

uint8_t LowPLC_Interp_Low_tag_cmp_eq_u8 = 0x30U;

uint8_t LowPLC_Interp_Low_tag_cmp_ne_u8 = 0x31U;

uint8_t LowPLC_Interp_Low_tag_cmp_lt_u8 = 0x32U;

uint8_t LowPLC_Interp_Low_tag_cmp_gt_u8 = 0x33U;

uint8_t LowPLC_Interp_Low_tag_cmp_le_u8 = 0x34U;

uint8_t LowPLC_Interp_Low_tag_cmp_ge_u8 = 0x35U;

uint8_t LowPLC_Interp_Low_tag_if_block_u8 = 0x40U;

uint8_t LowPLC_Interp_Low_tag_for_block_u8 = 0x41U;

uint8_t LowPLC_Interp_Low_tag_ton_call_u8 = 0x50U;

uint8_t LowPLC_Interp_Low_tag_tof_call_u8 = 0x51U;

uint8_t LowPLC_Interp_Low_tag_tp_call_u8 = 0x52U;

uint8_t LowPLC_Interp_Low_tag_ctu_call_u8 = 0x60U;

uint8_t LowPLC_Interp_Low_tag_ctd_call_u8 = 0x61U;

uint8_t LowPLC_Interp_Low_tag_ctud_call_u8 = 0x62U;

uint8_t LowPLC_Interp_Low_tag_sr_call_u8 = 0x70U;

uint8_t LowPLC_Interp_Low_tag_rs_call_u8 = 0x71U;

uint8_t LowPLC_Interp_Low_tag_rtrig_call_u8 = 0x72U;

uint8_t LowPLC_Interp_Low_tag_ftrig_call_u8 = 0x73U;

uint32_t LowPLC_Interp_Low_pt_us_to_ticks_low(uint32_t pt_us, uint32_t scan_period_us)
{
  if (scan_period_us == 0U)
    return 0U;
  else
    return pt_us / scan_period_us;
}

void
LowPLC_Interp_Low_exec_simple_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t off,
  uint8_t tag,
  uint16_t len,
  LowPLC_Interp_Low_low_pool p
)
{
  uint32_t poff = off + 3U;
  uint32_t len32 = (uint32_t)len;
  if (!(poff + len32 > code_len))
    if (tag == LowPLC_Interp_Low_tag_load_true_u8 && len >= 1U)
    {
      uint8_t idx = code[poff];
      uint32_t idx32 = (uint32_t)idx;
      if (idx32 < p.lp_n_bools)
        LowPLC_Interp_Low_set_bool_low(p, idx32, true);
    }
    else if (tag == LowPLC_Interp_Low_tag_load_false_u8 && len >= 1U)
    {
      uint8_t idx = code[poff];
      uint32_t idx32 = (uint32_t)idx;
      if (idx32 < p.lp_n_bools)
        LowPLC_Interp_Low_set_bool_low(p, idx32, false);
    }
    else if (tag == LowPLC_Interp_Low_tag_load_int_u8 && len >= 3U)
    {
      uint8_t idx = code[poff];
      uint32_t idx32 = (uint32_t)idx;
      if (idx32 < p.lp_n_ints)
      {
        int16_t v = LowPLC_Interp_Low_read_i16_le_low(code, poff + 1U);
        LowPLC_Interp_Low_set_int_low(p, idx32, v);
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_bool_not_u8 && len >= 2U)
    {
      uint8_t dst = code[poff];
      uint8_t src = code[poff + 1U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t src32 = (uint32_t)src;
      if (dst32 < p.lp_n_bools && src32 < p.lp_n_bools)
      {
        bool v = LowPLC_Interp_Low_get_bool_low(p, src32);
        LowPLC_Interp_Low_set_bool_low(p, dst32, !v);
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_bool_and_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_bools && a32 < p.lp_n_bools && b32 < p.lp_n_bools)
      {
        bool va = LowPLC_Interp_Low_get_bool_low(p, a32);
        bool vb = LowPLC_Interp_Low_get_bool_low(p, b32);
        LowPLC_Interp_Low_set_bool_low(p, dst32, va && vb);
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_bool_or_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_bools && a32 < p.lp_n_bools && b32 < p.lp_n_bools)
      {
        bool va = LowPLC_Interp_Low_get_bool_low(p, a32);
        bool vb = LowPLC_Interp_Low_get_bool_low(p, b32);
        LowPLC_Interp_Low_set_bool_low(p, dst32, va || vb);
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_bool_xor_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_bools && a32 < p.lp_n_bools && b32 < p.lp_n_bools)
      {
        bool va = LowPLC_Interp_Low_get_bool_low(p, a32);
        bool vb = LowPLC_Interp_Low_get_bool_low(p, b32);
        LowPLC_Interp_Low_set_bool_low(p, dst32, va != vb);
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_copy_bool_u8 && len >= 2U)
    {
      uint8_t dst = code[poff];
      uint8_t src = code[poff + 1U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t src32 = (uint32_t)src;
      if (dst32 < p.lp_n_bools && src32 < p.lp_n_bools)
      {
        bool v = LowPLC_Interp_Low_get_bool_low(p, src32);
        LowPLC_Interp_Low_set_bool_low(p, dst32, v);
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_int_add_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_ints && a32 < p.lp_n_ints && b32 < p.lp_n_ints)
      {
        int16_t va = LowPLC_Interp_Low_get_int_low(p, a32);
        int16_t vb = LowPLC_Interp_Low_get_int_low(p, b32);
        LowPLC_Interp_Low_set_int_low(p, dst32, LowPLC_Interp_Low_add_wrap_low(va, vb));
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_int_sub_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_ints && a32 < p.lp_n_ints && b32 < p.lp_n_ints)
      {
        int16_t va = LowPLC_Interp_Low_get_int_low(p, a32);
        int16_t vb = LowPLC_Interp_Low_get_int_low(p, b32);
        LowPLC_Interp_Low_set_int_low(p, dst32, LowPLC_Interp_Low_sub_wrap_low(va, vb));
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_int_mul_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_ints && a32 < p.lp_n_ints && b32 < p.lp_n_ints)
      {
        int16_t va = LowPLC_Interp_Low_get_int_low(p, a32);
        int16_t vb = LowPLC_Interp_Low_get_int_low(p, b32);
        LowPLC_Interp_Low_set_int_low(p, dst32, LowPLC_Interp_Low_mul_wrap_low(va, vb));
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_copy_int_u8 && len >= 2U)
    {
      uint8_t dst = code[poff];
      uint8_t src = code[poff + 1U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t src32 = (uint32_t)src;
      if (dst32 < p.lp_n_ints && src32 < p.lp_n_ints)
      {
        int16_t v = LowPLC_Interp_Low_get_int_low(p, src32);
        LowPLC_Interp_Low_set_int_low(p, dst32, v);
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_cmp_eq_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_bools && a32 < p.lp_n_ints && b32 < p.lp_n_ints)
      {
        int16_t va = LowPLC_Interp_Low_get_int_low(p, a32);
        int16_t vb = LowPLC_Interp_Low_get_int_low(p, b32);
        LowPLC_Interp_Low_set_bool_low(p, dst32, va == vb);
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_cmp_ne_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_bools && a32 < p.lp_n_ints && b32 < p.lp_n_ints)
      {
        int16_t va = LowPLC_Interp_Low_get_int_low(p, a32);
        int16_t vb = LowPLC_Interp_Low_get_int_low(p, b32);
        LowPLC_Interp_Low_set_bool_low(p, dst32, !(va == vb));
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_cmp_lt_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_bools && a32 < p.lp_n_ints && b32 < p.lp_n_ints)
      {
        int16_t va = LowPLC_Interp_Low_get_int_low(p, a32);
        int16_t vb = LowPLC_Interp_Low_get_int_low(p, b32);
        LowPLC_Interp_Low_set_bool_low(p, dst32, va < vb);
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_cmp_gt_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_bools && a32 < p.lp_n_ints && b32 < p.lp_n_ints)
      {
        int16_t va = LowPLC_Interp_Low_get_int_low(p, a32);
        int16_t vb = LowPLC_Interp_Low_get_int_low(p, b32);
        LowPLC_Interp_Low_set_bool_low(p, dst32, va > vb);
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_cmp_le_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_bools && a32 < p.lp_n_ints && b32 < p.lp_n_ints)
      {
        int16_t va = LowPLC_Interp_Low_get_int_low(p, a32);
        int16_t vb = LowPLC_Interp_Low_get_int_low(p, b32);
        LowPLC_Interp_Low_set_bool_low(p, dst32, va <= vb);
      }
    }
    else if (tag == LowPLC_Interp_Low_tag_cmp_ge_u8 && len >= 3U)
    {
      uint8_t dst = code[poff];
      uint8_t a = code[poff + 1U];
      uint8_t b = code[poff + 2U];
      uint32_t dst32 = (uint32_t)dst;
      uint32_t a32 = (uint32_t)a;
      uint32_t b32 = (uint32_t)b;
      if (dst32 < p.lp_n_bools && a32 < p.lp_n_ints && b32 < p.lp_n_ints)
      {
        int16_t va = LowPLC_Interp_Low_get_int_low(p, a32);
        int16_t vb = LowPLC_Interp_Low_get_int_low(p, b32);
        LowPLC_Interp_Low_set_bool_low(p, dst32, va >= vb);
      }
    }
}

uint8_t LowPLC_Interp_Low_get_sr_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx)
{
  return p.lp_srs[idx];
}

void LowPLC_Interp_Low_set_sr_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx, uint8_t v)
{
  p.lp_srs[idx] = v;
}

uint8_t LowPLC_Interp_Low_get_rs_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx)
{
  return p.lp_rss[idx];
}

void LowPLC_Interp_Low_set_rs_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx, uint8_t v)
{
  p.lp_rss[idx] = v;
}

uint8_t LowPLC_Interp_Low_get_rtrig_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx)
{
  return p.lp_rtrigs[idx];
}

void
LowPLC_Interp_Low_set_rtrig_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx, uint8_t v)
{
  p.lp_rtrigs[idx] = v;
}

uint8_t LowPLC_Interp_Low_get_ftrig_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx)
{
  return p.lp_ftrigs[idx];
}

void
LowPLC_Interp_Low_set_ftrig_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx, uint8_t v)
{
  p.lp_ftrigs[idx] = v;
}

LowPLC_Interp_Low_ctu_flat
LowPLC_Interp_Low_get_ctu_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx)
{
  return p.lp_ctus[idx];
}

void
LowPLC_Interp_Low_set_ctu_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_ctu_flat v
)
{
  p.lp_ctus[idx] = v;
}

LowPLC_Interp_Low_ctd_flat
LowPLC_Interp_Low_get_ctd_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx)
{
  return p.lp_ctds[idx];
}

void
LowPLC_Interp_Low_set_ctd_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_ctd_flat v
)
{
  p.lp_ctds[idx] = v;
}

LowPLC_Interp_Low_ctud_flat
LowPLC_Interp_Low_get_ctud_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx)
{
  return p.lp_ctuds[idx];
}

void
LowPLC_Interp_Low_set_ctud_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_ctud_flat v
)
{
  p.lp_ctuds[idx] = v;
}

LowPLC_Interp_Low_ton_flat
LowPLC_Interp_Low_get_ton_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx)
{
  return p.lp_tons[idx];
}

void
LowPLC_Interp_Low_set_ton_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_ton_flat v
)
{
  p.lp_tons[idx] = v;
}

LowPLC_Interp_Low_tof_flat
LowPLC_Interp_Low_get_tof_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx)
{
  return p.lp_tofs[idx];
}

void
LowPLC_Interp_Low_set_tof_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_tof_flat v
)
{
  p.lp_tofs[idx] = v;
}

LowPLC_Interp_Low_tp_flat
LowPLC_Interp_Low_get_tp_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx)
{
  return p.lp_tps[idx];
}

void
LowPLC_Interp_Low_set_tp_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_tp_flat v
)
{
  p.lp_tps[idx] = v;
}

void
LowPLC_Interp_Low_exec_fb_call_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t off,
  uint8_t tag,
  uint16_t len,
  LowPLC_Interp_Low_low_pool p
)
{
  KRML_MAYBE_UNUSED_VAR(code_len);
  uint32_t poff = off + 3U;
  if (tag == LowPLC_Interp_Low_tag_sr_call_u8 && len >= 4U)
  {
    uint8_t idx_raw = code[poff];
    uint32_t idx = (uint32_t)idx_raw;
    if (idx < p.lp_n_sr)
    {
      uint8_t _r1 = code[poff + 1U];
      uint32_t s1_b = (uint32_t)_r1;
      uint8_t _r2 = code[poff + 2U];
      uint32_t r_b = (uint32_t)_r2;
      uint8_t _r3 = code[poff + 3U];
      uint32_t q1_b = (uint32_t)_r3;
      if (s1_b < p.lp_n_bools && r_b < p.lp_n_bools && q1_b < p.lp_n_bools)
      {
        uint8_t s = LowPLC_Interp_Low_get_sr_state_low(p, idx);
        bool old_q = s != 0U;
        bool s1_v = LowPLC_Interp_Low_get_bool_low(p, s1_b);
        bool r_v = LowPLC_Interp_Low_get_bool_low(p, r_b);
        bool new_q = s1_v || !r_v && old_q;
        uint8_t ite;
        if (new_q)
          ite = 1U;
        else
          ite = 0U;
        LowPLC_Interp_Low_set_sr_state_low(p, idx, ite);
        LowPLC_Interp_Low_set_bool_low(p, q1_b, new_q);
      }
    }
  }
  else if (tag == LowPLC_Interp_Low_tag_rs_call_u8 && len >= 4U)
  {
    uint8_t idx_raw = code[poff];
    uint32_t idx = (uint32_t)idx_raw;
    if (idx < p.lp_n_rs)
    {
      uint8_t _r4 = code[poff + 1U];
      uint32_t s_b = (uint32_t)_r4;
      uint8_t _r5 = code[poff + 2U];
      uint32_t r1_b = (uint32_t)_r5;
      uint8_t _r6 = code[poff + 3U];
      uint32_t q1_b = (uint32_t)_r6;
      if (s_b < p.lp_n_bools && r1_b < p.lp_n_bools && q1_b < p.lp_n_bools)
      {
        uint8_t s = LowPLC_Interp_Low_get_rs_state_low(p, idx);
        bool old_q = s != 0U;
        bool s_v = LowPLC_Interp_Low_get_bool_low(p, s_b);
        bool r1_v = LowPLC_Interp_Low_get_bool_low(p, r1_b);
        bool new_q = !r1_v && (s_v || old_q);
        uint8_t ite;
        if (new_q)
          ite = 1U;
        else
          ite = 0U;
        LowPLC_Interp_Low_set_rs_state_low(p, idx, ite);
        LowPLC_Interp_Low_set_bool_low(p, q1_b, new_q);
      }
    }
  }
  else if (tag == LowPLC_Interp_Low_tag_rtrig_call_u8 && len >= 3U)
  {
    uint8_t idx_raw = code[poff];
    uint32_t idx = (uint32_t)idx_raw;
    if (idx < p.lp_n_rtrig)
    {
      uint8_t _r7 = code[poff + 1U];
      uint32_t clk_b = (uint32_t)_r7;
      uint8_t _r8 = code[poff + 2U];
      uint32_t q_b = (uint32_t)_r8;
      if (clk_b < p.lp_n_bools && q_b < p.lp_n_bools)
      {
        uint8_t s = LowPLC_Interp_Low_get_rtrig_state_low(p, idx);
        bool old_m = s != 0U;
        bool clk = LowPLC_Interp_Low_get_bool_low(p, clk_b);
        bool q = clk && !old_m;
        uint8_t ite;
        if (clk)
          ite = 1U;
        else
          ite = 0U;
        LowPLC_Interp_Low_set_rtrig_state_low(p, idx, ite);
        LowPLC_Interp_Low_set_bool_low(p, q_b, q);
      }
    }
  }
  else if (tag == LowPLC_Interp_Low_tag_ftrig_call_u8 && len >= 3U)
  {
    uint8_t idx_raw = code[poff];
    uint32_t idx = (uint32_t)idx_raw;
    if (idx < p.lp_n_ftrig)
    {
      uint8_t _r9 = code[poff + 1U];
      uint32_t clk_b = (uint32_t)_r9;
      uint8_t _r10 = code[poff + 2U];
      uint32_t q_b = (uint32_t)_r10;
      if (clk_b < p.lp_n_bools && q_b < p.lp_n_bools)
      {
        uint8_t s = LowPLC_Interp_Low_get_ftrig_state_low(p, idx);
        bool old_m = s != 0U;
        bool clk = LowPLC_Interp_Low_get_bool_low(p, clk_b);
        bool q = !clk && old_m;
        uint8_t ite;
        if (clk)
          ite = 1U;
        else
          ite = 0U;
        LowPLC_Interp_Low_set_ftrig_state_low(p, idx, ite);
        LowPLC_Interp_Low_set_bool_low(p, q_b, q);
      }
    }
  }
  else if (tag == LowPLC_Interp_Low_tag_ctu_call_u8 && len >= 6U)
  {
    uint8_t idx_raw = code[poff];
    uint32_t idx = (uint32_t)idx_raw;
    if (idx < p.lp_n_ctu)
    {
      uint8_t _r11 = code[poff + 1U];
      uint32_t cu_b = (uint32_t)_r11;
      uint8_t _r12 = code[poff + 2U];
      uint32_t r_b = (uint32_t)_r12;
      uint8_t _r13 = code[poff + 3U];
      uint32_t pv_i = (uint32_t)_r13;
      uint8_t _r14 = code[poff + 4U];
      uint32_t q_b = (uint32_t)_r14;
      uint8_t _r15 = code[poff + 5U];
      uint32_t cv_i = (uint32_t)_r15;
      if
      (
        cu_b < p.lp_n_bools && r_b < p.lp_n_bools && pv_i < p.lp_n_ints && q_b < p.lp_n_bools &&
          cv_i < p.lp_n_ints
      )
      {
        LowPLC_Interp_Low_ctu_flat s = LowPLC_Interp_Low_get_ctu_state_low(p, idx);
        bool cu = LowPLC_Interp_Low_get_bool_low(p, cu_b);
        bool r = LowPLC_Interp_Low_get_bool_low(p, r_b);
        int16_t pv = LowPLC_Interp_Low_get_int_low(p, pv_i);
        bool prev_cu = s.ctuf_prev_cu != 0U;
        int16_t cv = s.ctuf_cv;
        int16_t new_cv;
        if (r)
          new_cv = (int16_t)0;
        else if (cu && !prev_cu && cv < pv)
          new_cv = LowPLC_Interp_Low_add_wrap_low(cv, (int16_t)1);
        else
          new_cv = cv;
        uint8_t ite;
        if (cu)
          ite = 1U;
        else
          ite = 0U;
        LowPLC_Interp_Low_set_ctu_state_low(p,
          idx,
          ((LowPLC_Interp_Low_ctu_flat){ .ctuf_cv = new_cv, .ctuf_prev_cu = ite }));
        LowPLC_Interp_Low_set_bool_low(p, q_b, new_cv >= pv);
        LowPLC_Interp_Low_set_int_low(p, cv_i, new_cv);
      }
    }
  }
  else if (tag == LowPLC_Interp_Low_tag_ctd_call_u8 && len >= 6U)
  {
    uint8_t idx_raw = code[poff];
    uint32_t idx = (uint32_t)idx_raw;
    if (idx < p.lp_n_ctd)
    {
      uint8_t _r16 = code[poff + 1U];
      uint32_t cd_b = (uint32_t)_r16;
      uint8_t _r17 = code[poff + 2U];
      uint32_t ld_b = (uint32_t)_r17;
      uint8_t _r18 = code[poff + 3U];
      uint32_t pv_i = (uint32_t)_r18;
      uint8_t _r19 = code[poff + 4U];
      uint32_t q_b = (uint32_t)_r19;
      uint8_t _r20 = code[poff + 5U];
      uint32_t cv_i = (uint32_t)_r20;
      if
      (
        cd_b < p.lp_n_bools && ld_b < p.lp_n_bools && pv_i < p.lp_n_ints && q_b < p.lp_n_bools &&
          cv_i < p.lp_n_ints
      )
      {
        LowPLC_Interp_Low_ctd_flat s = LowPLC_Interp_Low_get_ctd_state_low(p, idx);
        bool cd = LowPLC_Interp_Low_get_bool_low(p, cd_b);
        bool ld = LowPLC_Interp_Low_get_bool_low(p, ld_b);
        int16_t pv = LowPLC_Interp_Low_get_int_low(p, pv_i);
        bool prev_cd = s.ctdf_prev_cd != 0U;
        int16_t cv = s.ctdf_cv;
        int16_t new_cv;
        if (ld)
          new_cv = pv;
        else if (cd && !prev_cd && cv > (int16_t)0)
          new_cv = LowPLC_Interp_Low_sub_wrap_low(cv, (int16_t)1);
        else
          new_cv = cv;
        uint8_t ite;
        if (cd)
          ite = 1U;
        else
          ite = 0U;
        LowPLC_Interp_Low_set_ctd_state_low(p,
          idx,
          ((LowPLC_Interp_Low_ctd_flat){ .ctdf_cv = new_cv, .ctdf_prev_cd = ite }));
        LowPLC_Interp_Low_set_bool_low(p, q_b, new_cv <= (int16_t)0);
        LowPLC_Interp_Low_set_int_low(p, cv_i, new_cv);
      }
    }
  }
  else if (tag == LowPLC_Interp_Low_tag_ctud_call_u8 && len >= 9U)
  {
    uint8_t idx_raw = code[poff];
    uint32_t idx = (uint32_t)idx_raw;
    if (idx < p.lp_n_ctud)
    {
      uint8_t _r21 = code[poff + 1U];
      uint32_t cu_b = (uint32_t)_r21;
      uint8_t _r22 = code[poff + 2U];
      uint32_t cd_b = (uint32_t)_r22;
      uint8_t _r23 = code[poff + 3U];
      uint32_t r_b = (uint32_t)_r23;
      uint8_t _r24 = code[poff + 4U];
      uint32_t ld_b = (uint32_t)_r24;
      uint8_t _r25 = code[poff + 5U];
      uint32_t pv_i = (uint32_t)_r25;
      uint8_t _r26 = code[poff + 6U];
      uint32_t qu_b = (uint32_t)_r26;
      uint8_t _r27 = code[poff + 7U];
      uint32_t qd_b = (uint32_t)_r27;
      uint8_t _r28 = code[poff + 8U];
      uint32_t cv_i = (uint32_t)_r28;
      if
      (
        cu_b < p.lp_n_bools && cd_b < p.lp_n_bools && r_b < p.lp_n_bools && ld_b < p.lp_n_bools &&
          pv_i < p.lp_n_ints
        && qu_b < p.lp_n_bools
        && qd_b < p.lp_n_bools
        && cv_i < p.lp_n_ints
      )
      {
        LowPLC_Interp_Low_ctud_flat s = LowPLC_Interp_Low_get_ctud_state_low(p, idx);
        bool cu = LowPLC_Interp_Low_get_bool_low(p, cu_b);
        bool cd = LowPLC_Interp_Low_get_bool_low(p, cd_b);
        bool r = LowPLC_Interp_Low_get_bool_low(p, r_b);
        bool ld = LowPLC_Interp_Low_get_bool_low(p, ld_b);
        int16_t pv = LowPLC_Interp_Low_get_int_low(p, pv_i);
        bool rising_cu = cu && !(s.ctudf_prev_cu != 0U);
        bool rising_cd = cd && !(s.ctudf_prev_cd != 0U);
        int16_t cv = s.ctudf_cv;
        int16_t new_cv;
        if (r)
          new_cv = (int16_t)0;
        else if (ld)
          new_cv = pv;
        else if (rising_cu && rising_cd)
          new_cv = cv;
        else
        {
          int16_t v1;
          if (rising_cu && cv < pv)
            v1 = LowPLC_Interp_Low_add_wrap_low(cv, (int16_t)1);
          else
            v1 = cv;
          if (rising_cd && v1 > (int16_t)0)
            new_cv = LowPLC_Interp_Low_sub_wrap_low(v1, (int16_t)1);
          else
            new_cv = v1;
        }
        uint8_t ite0;
        if (cu)
          ite0 = 1U;
        else
          ite0 = 0U;
        uint8_t ite;
        if (cd)
          ite = 1U;
        else
          ite = 0U;
        LowPLC_Interp_Low_set_ctud_state_low(p,
          idx,
          (
            (LowPLC_Interp_Low_ctud_flat){
              .ctudf_cv = new_cv,
              .ctudf_prev_cu = ite0,
              .ctudf_prev_cd = ite
            }
          ));
        LowPLC_Interp_Low_set_bool_low(p, qu_b, new_cv >= pv);
        LowPLC_Interp_Low_set_bool_low(p, qd_b, new_cv <= (int16_t)0);
        LowPLC_Interp_Low_set_int_low(p, cv_i, new_cv);
      }
    }
  }
  else if (tag == LowPLC_Interp_Low_tag_ton_call_u8 && len >= 7U)
  {
    uint8_t idx_raw = code[poff];
    uint32_t idx = (uint32_t)idx_raw;
    if (idx < p.lp_n_ton)
    {
      uint8_t _r29 = code[poff + 1U];
      uint32_t in_b = (uint32_t)_r29;
      uint32_t pt_us = LowPLC_Interp_Low_read_u32_le_low(code, poff + 2U);
      uint8_t _r30 = code[poff + 6U];
      uint32_t q_b = (uint32_t)_r30;
      if (in_b < p.lp_n_bools && q_b < p.lp_n_bools)
      {
        uint32_t pt_ticks = LowPLC_Interp_Low_pt_us_to_ticks_low(pt_us, p.lp_scan_period_us);
        LowPLC_Interp_Low_ton_flat s = LowPLC_Interp_Low_get_ton_state_low(p, idx);
        if (p.lp_tick >= s.tf_start)
        {
          bool in_v = LowPLC_Interp_Low_get_bool_low(p, in_b);
          uint8_t phase = s.tf_phase;
          if (phase == 0U)
            if (in_v)
            {
              LowPLC_Interp_Low_set_ton_state_low(p,
                idx,
                ((LowPLC_Interp_Low_ton_flat){ .tf_phase = 1U, .tf_start = p.lp_tick }));
              LowPLC_Interp_Low_set_bool_low(p, q_b, false);
            }
            else
              LowPLC_Interp_Low_set_bool_low(p, q_b, false);
          else if (phase == 1U)
            if (!in_v)
            {
              LowPLC_Interp_Low_set_ton_state_low(p,
                idx,
                ((LowPLC_Interp_Low_ton_flat){ .tf_phase = 0U, .tf_start = 0U }));
              LowPLC_Interp_Low_set_bool_low(p, q_b, false);
            }
            else
            {
              uint32_t elapsed = p.lp_tick - s.tf_start;
              if (elapsed >= pt_ticks)
              {
                LowPLC_Interp_Low_set_ton_state_low(p,
                  idx,
                  ((LowPLC_Interp_Low_ton_flat){ .tf_phase = 2U, .tf_start = s.tf_start }));
                LowPLC_Interp_Low_set_bool_low(p, q_b, true);
              }
              else
                LowPLC_Interp_Low_set_bool_low(p, q_b, false);
            }
          else if (!in_v)
          {
            LowPLC_Interp_Low_set_ton_state_low(p,
              idx,
              ((LowPLC_Interp_Low_ton_flat){ .tf_phase = 0U, .tf_start = 0U }));
            LowPLC_Interp_Low_set_bool_low(p, q_b, false);
          }
          else
            LowPLC_Interp_Low_set_bool_low(p, q_b, true);
        }
      }
    }
  }
  else if (tag == LowPLC_Interp_Low_tag_tof_call_u8 && len >= 7U)
  {
    uint8_t idx_raw = code[poff];
    uint32_t idx = (uint32_t)idx_raw;
    if (idx < p.lp_n_tof)
    {
      uint8_t _r31 = code[poff + 1U];
      uint32_t in_b = (uint32_t)_r31;
      uint32_t pt_us = LowPLC_Interp_Low_read_u32_le_low(code, poff + 2U);
      uint8_t _r32 = code[poff + 6U];
      uint32_t q_b = (uint32_t)_r32;
      if (in_b < p.lp_n_bools && q_b < p.lp_n_bools)
      {
        uint32_t pt_ticks = LowPLC_Interp_Low_pt_us_to_ticks_low(pt_us, p.lp_scan_period_us);
        LowPLC_Interp_Low_tof_flat s = LowPLC_Interp_Low_get_tof_state_low(p, idx);
        if (p.lp_tick >= s.tff_start)
        {
          bool in_v = LowPLC_Interp_Low_get_bool_low(p, in_b);
          uint8_t phase = s.tff_phase;
          if (phase == 0U)
            if (in_v)
            {
              LowPLC_Interp_Low_set_tof_state_low(p,
                idx,
                (
                  (LowPLC_Interp_Low_tof_flat){
                    .tff_phase = 0U,
                    .tff_prev_in = 1U,
                    .tff_start = s.tff_start
                  }
                ));
              LowPLC_Interp_Low_set_bool_low(p, q_b, true);
            }
            else if (s.tff_prev_in != 0U)
            {
              LowPLC_Interp_Low_set_tof_state_low(p,
                idx,
                (
                  (LowPLC_Interp_Low_tof_flat){
                    .tff_phase = 1U,
                    .tff_prev_in = 0U,
                    .tff_start = p.lp_tick
                  }
                ));
              LowPLC_Interp_Low_set_bool_low(p, q_b, true);
            }
            else
              LowPLC_Interp_Low_set_bool_low(p, q_b, false);
          else if (phase == 1U)
            if (in_v)
            {
              LowPLC_Interp_Low_set_tof_state_low(p,
                idx,
                (
                  (LowPLC_Interp_Low_tof_flat){
                    .tff_phase = 0U,
                    .tff_prev_in = 1U,
                    .tff_start = s.tff_start
                  }
                ));
              LowPLC_Interp_Low_set_bool_low(p, q_b, true);
            }
            else
            {
              uint32_t elapsed = p.lp_tick - s.tff_start;
              if (elapsed >= pt_ticks)
              {
                LowPLC_Interp_Low_set_tof_state_low(p,
                  idx,
                  (
                    (LowPLC_Interp_Low_tof_flat){
                      .tff_phase = 0U,
                      .tff_prev_in = 0U,
                      .tff_start = s.tff_start
                    }
                  ));
                LowPLC_Interp_Low_set_bool_low(p, q_b, false);
              }
              else
                LowPLC_Interp_Low_set_bool_low(p, q_b, true);
            }
          else
            LowPLC_Interp_Low_set_bool_low(p, q_b, false);
        }
      }
    }
  }
  else if (tag == LowPLC_Interp_Low_tag_tp_call_u8 && len >= 7U)
  {
    uint8_t idx_raw = code[poff];
    uint32_t idx = (uint32_t)idx_raw;
    if (idx < p.lp_n_tp)
    {
      uint8_t _r33 = code[poff + 1U];
      uint32_t in_b = (uint32_t)_r33;
      uint32_t pt_us = LowPLC_Interp_Low_read_u32_le_low(code, poff + 2U);
      uint8_t _r34 = code[poff + 6U];
      uint32_t q_b = (uint32_t)_r34;
      if (in_b < p.lp_n_bools && q_b < p.lp_n_bools)
      {
        uint32_t pt_ticks = LowPLC_Interp_Low_pt_us_to_ticks_low(pt_us, p.lp_scan_period_us);
        LowPLC_Interp_Low_tp_flat s = LowPLC_Interp_Low_get_tp_state_low(p, idx);
        if (p.lp_tick >= s.tpf_start)
        {
          bool in_v = LowPLC_Interp_Low_get_bool_low(p, in_b);
          uint8_t phase = s.tpf_phase;
          if (phase == 0U)
            if (in_v && !(s.tpf_prev_in != 0U))
            {
              LowPLC_Interp_Low_set_tp_state_low(p,
                idx,
                (
                  (LowPLC_Interp_Low_tp_flat){
                    .tpf_phase = 1U,
                    .tpf_prev_in = 1U,
                    .tpf_start = p.lp_tick
                  }
                ));
              LowPLC_Interp_Low_set_bool_low(p, q_b, true);
            }
            else
            {
              uint8_t ite;
              if (in_v)
                ite = 1U;
              else
                ite = 0U;
              LowPLC_Interp_Low_set_tp_state_low(p,
                idx,
                (
                  (LowPLC_Interp_Low_tp_flat){
                    .tpf_phase = 0U,
                    .tpf_prev_in = ite,
                    .tpf_start = s.tpf_start
                  }
                ));
              LowPLC_Interp_Low_set_bool_low(p, q_b, false);
            }
          else if (phase == 1U)
          {
            uint32_t elapsed = p.lp_tick - s.tpf_start;
            if (elapsed >= pt_ticks)
            {
              uint8_t ite;
              if (in_v)
                ite = 1U;
              else
                ite = 0U;
              LowPLC_Interp_Low_set_tp_state_low(p,
                idx,
                (
                  (LowPLC_Interp_Low_tp_flat){
                    .tpf_phase = 0U,
                    .tpf_prev_in = ite,
                    .tpf_start = s.tpf_start
                  }
                ));
              LowPLC_Interp_Low_set_bool_low(p, q_b, false);
            }
            else
            {
              uint8_t ite;
              if (in_v)
                ite = 1U;
              else
                ite = 0U;
              LowPLC_Interp_Low_set_tp_state_low(p,
                idx,
                (
                  (LowPLC_Interp_Low_tp_flat){
                    .tpf_phase = 1U,
                    .tpf_prev_in = ite,
                    .tpf_start = s.tpf_start
                  }
                ));
              LowPLC_Interp_Low_set_bool_low(p, q_b, true);
            }
          }
          else
            LowPLC_Interp_Low_set_bool_low(p, q_b, false);
        }
      }
    }
  }
}

void
LowPLC_Interp_Low_exec_stmts_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t off,
  uint32_t rem,
  LowPLC_Interp_Low_low_pool p,
  uint32_t gas
)
{
  if (!(gas == 0U || rem < 3U))
    if (!(off + 3U > code_len))
    {
      uint8_t r0 = code[off];
      uint8_t tag = r0;
      uint16_t len16 = LowPLC_Interp_Low_read_u16_le_low(code, off + 1U);
      uint32_t len32 = (uint32_t)len16;
      if (!(3U + len32 > rem))
        if (!(len32 > code_len - off - 3U))
        {
          uint32_t next_off = off + 3U + len32;
          uint32_t consumed = 3U + len32;
          uint32_t new_rem = rem - consumed;
          if (tag == LowPLC_Interp_Low_tag_if_block_u8)
            LowPLC_Interp_Low_exec_if_block_low(code, code_len, off + 3U, len16, p, gas - 1U);
          else if (tag == LowPLC_Interp_Low_tag_for_block_u8)
            LowPLC_Interp_Low_exec_for_block_low(code, code_len, off + 3U, len16, p, gas - 1U);
          else
          {
            LowPLC_Interp_Low_exec_simple_low(code, code_len, off, tag, len16, p);
            LowPLC_Interp_Low_exec_fb_call_low(code, code_len, off, tag, len16, p);
          }
          LowPLC_Interp_Low_exec_stmts_low(code, code_len, next_off, new_rem, p, gas - 1U);
        }
    }
}

void
LowPLC_Interp_Low_exec_if_block_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t poff,
  uint16_t plen,
  LowPLC_Interp_Low_low_pool p,
  uint32_t gas
)
{
  KRML_MAYBE_UNUSED_VAR(plen);
  if (!(gas == 0U))
    if (!(code_len - poff < 7U))
    {
      uint8_t cond_raw = code[poff];
      uint32_t cond_idx = (uint32_t)cond_raw;
      uint16_t then_len16 = LowPLC_Interp_Low_read_u16_le_low(code, poff + 3U);
      uint16_t else_len16 = LowPLC_Interp_Low_read_u16_le_low(code, poff + 5U);
      uint32_t then_len = (uint32_t)then_len16;
      uint32_t else_len = (uint32_t)else_len16;
      uint32_t then_off = poff + 7U;
      if (!(then_len > code_len - then_off))
      {
        uint32_t else_off = then_off + then_len;
        if (!(else_len > code_len - else_off))
          if (cond_idx < p.lp_n_bools)
          {
            bool cond_v = LowPLC_Interp_Low_get_bool_low(p, cond_idx);
            if (cond_v)
              LowPLC_Interp_Low_exec_stmts_low(code, code_len, then_off, then_len, p, gas - 1U);
            else if (else_len > 0U)
              LowPLC_Interp_Low_exec_stmts_low(code, code_len, else_off, else_len, p, gas - 1U);
          }
      }
    }
}

void
LowPLC_Interp_Low_exec_for_block_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t poff,
  uint16_t plen,
  LowPLC_Interp_Low_low_pool p,
  uint32_t gas
)
{
  KRML_MAYBE_UNUSED_VAR(plen);
  if (!(gas == 0U))
    if (!(code_len - poff < 8U))
    {
      uint8_t idx_raw = code[poff];
      uint32_t idx32 = (uint32_t)idx_raw;
      int16_t start_v = LowPLC_Interp_Low_read_i16_le_low(code, poff + 1U);
      int16_t end_v = LowPLC_Interp_Low_read_i16_le_low(code, poff + 3U);
      uint16_t body_len16 = LowPLC_Interp_Low_read_u16_le_low(code, poff + 6U);
      uint32_t body_len = (uint32_t)body_len16;
      uint32_t body_off = poff + 8U;
      if (!(body_len > code_len - body_off))
        if (idx32 < p.lp_n_ints)
        {
          LowPLC_Interp_Low_set_int_low(p, idx32, start_v);
          uint32_t iters;
          if (end_v >= start_v)
          {
            int32_t e32 = (int32_t)end_v;
            int32_t s32 = (int32_t)start_v;
            int32_t diff_plus_1 = e32 - s32 + (int32_t)1;
            if (diff_plus_1 >= (int32_t)0)
              iters = (uint32_t)diff_plus_1;
            else
              iters = 0U;
          }
          else
            iters = 0U;
          LowPLC_Interp_Low_exec_for_iter_low(code,
            code_len,
            body_off,
            body_len,
            idx32,
            end_v,
            p,
            iters,
            gas - 1U);
        }
    }
}

void
LowPLC_Interp_Low_exec_for_iter_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t body_off,
  uint32_t body_len,
  uint32_t idx_i,
  int16_t end_v,
  LowPLC_Interp_Low_low_pool p,
  uint32_t iters_left,
  uint32_t gas
)
{
  if (!(gas == 0U || iters_left == 0U))
  {
    LowPLC_Interp_Low_exec_stmts_low(code, code_len, body_off, body_len, p, gas - 1U);
    int16_t cur = LowPLC_Interp_Low_get_int_low(p, idx_i);
    int16_t next = LowPLC_Interp_Low_add_wrap_low(cur, (int16_t)1);
    LowPLC_Interp_Low_set_int_low(p, idx_i, next);
    LowPLC_Interp_Low_exec_for_iter_low(code,
      code_len,
      body_off,
      body_len,
      idx_i,
      end_v,
      p,
      iters_left - 1U,
      gas - 1U);
  }
}

