/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/iamfo470/phd/everparse/opt/karamel/krml -fstar /home/iamfo470/phd/everparse/opt/FStar/out/bin/fstar.exe -skip-compilation -tmpdir build_low -drop FStar.*,LowStar.*,Prims,C.* -warn-error -2 -fsopt --include -fsopt src src/LowPLC.Interp.Low.fst
  F* version: <unknown>
  KaRaMeL version: fb36fecb
 */

#ifndef LowPLC_Interp_Low_H
#define LowPLC_Interp_Low_H

#include "krmllib.h"

typedef struct LowPLC_Interp_Low_ton_flat_s
{
  uint8_t tf_phase;
  uint32_t tf_start;
}
LowPLC_Interp_Low_ton_flat;

typedef struct LowPLC_Interp_Low_tof_flat_s
{
  uint8_t tff_phase;
  uint8_t tff_prev_in;
  uint32_t tff_start;
}
LowPLC_Interp_Low_tof_flat;

typedef struct LowPLC_Interp_Low_tp_flat_s
{
  uint8_t tpf_phase;
  uint8_t tpf_prev_in;
  uint32_t tpf_start;
}
LowPLC_Interp_Low_tp_flat;

typedef struct LowPLC_Interp_Low_ctu_flat_s
{
  int16_t ctuf_cv;
  uint8_t ctuf_prev_cu;
}
LowPLC_Interp_Low_ctu_flat;

typedef struct LowPLC_Interp_Low_ctd_flat_s
{
  int16_t ctdf_cv;
  uint8_t ctdf_prev_cd;
}
LowPLC_Interp_Low_ctd_flat;

typedef struct LowPLC_Interp_Low_ctud_flat_s
{
  int16_t ctudf_cv;
  uint8_t ctudf_prev_cu;
  uint8_t ctudf_prev_cd;
}
LowPLC_Interp_Low_ctud_flat;

typedef uint8_t LowPLC_Interp_Low_sr_flat;

typedef uint8_t LowPLC_Interp_Low_rs_flat;

typedef uint8_t LowPLC_Interp_Low_rtrig_flat;

typedef uint8_t LowPLC_Interp_Low_ftrig_flat;

typedef struct LowPLC_Interp_Low_low_pool_s
{
  bool *lp_bools;
  int16_t *lp_ints;
  LowPLC_Interp_Low_ton_flat *lp_tons;
  LowPLC_Interp_Low_tof_flat *lp_tofs;
  LowPLC_Interp_Low_tp_flat *lp_tps;
  LowPLC_Interp_Low_ctu_flat *lp_ctus;
  LowPLC_Interp_Low_ctd_flat *lp_ctds;
  LowPLC_Interp_Low_ctud_flat *lp_ctuds;
  uint8_t *lp_srs;
  uint8_t *lp_rss;
  uint8_t *lp_rtrigs;
  uint8_t *lp_ftrigs;
  uint32_t lp_n_bools;
  uint32_t lp_n_ints;
  uint32_t lp_n_ton;
  uint32_t lp_n_tof;
  uint32_t lp_n_tp;
  uint32_t lp_n_ctu;
  uint32_t lp_n_ctd;
  uint32_t lp_n_ctud;
  uint32_t lp_n_sr;
  uint32_t lp_n_rs;
  uint32_t lp_n_rtrig;
  uint32_t lp_n_ftrig;
  uint32_t lp_tick;
  uint32_t lp_scan_period_us;
}
LowPLC_Interp_Low_low_pool;

typedef void *LowPLC_Interp_Low_pool_live;

typedef void *LowPLC_Interp_Low_pool_lengths_ok;

typedef void *LowPLC_Interp_Low_pool_disjoint;

typedef void *LowPLC_Interp_Low_pool_valid;

bool LowPLC_Interp_Low_get_bool_low(LowPLC_Interp_Low_low_pool p, uint32_t i);

void LowPLC_Interp_Low_set_bool_low(LowPLC_Interp_Low_low_pool p, uint32_t i, bool v);

int16_t LowPLC_Interp_Low_get_int_low(LowPLC_Interp_Low_low_pool p, uint32_t i);

void LowPLC_Interp_Low_set_int_low(LowPLC_Interp_Low_low_pool p, uint32_t i, int16_t v);

uint16_t LowPLC_Interp_Low_read_u16_le_low(uint8_t *code, uint32_t off);

uint32_t LowPLC_Interp_Low_read_u32_le_low(uint8_t *code, uint32_t off);

int16_t LowPLC_Interp_Low_read_i16_le_low(uint8_t *code, uint32_t off);

int16_t LowPLC_Interp_Low_wrap_i16_low(int16_t x);

int16_t LowPLC_Interp_Low_add_wrap_low(int16_t a, int16_t b);

int16_t LowPLC_Interp_Low_sub_wrap_low(int16_t a, int16_t b);

int16_t LowPLC_Interp_Low_mul_wrap_low(int16_t a, int16_t b);

extern uint8_t LowPLC_Interp_Low_tag_load_true_u8;

extern uint8_t LowPLC_Interp_Low_tag_load_false_u8;

extern uint8_t LowPLC_Interp_Low_tag_load_int_u8;

extern uint8_t LowPLC_Interp_Low_tag_bool_not_u8;

extern uint8_t LowPLC_Interp_Low_tag_bool_and_u8;

extern uint8_t LowPLC_Interp_Low_tag_bool_or_u8;

extern uint8_t LowPLC_Interp_Low_tag_bool_xor_u8;

extern uint8_t LowPLC_Interp_Low_tag_copy_bool_u8;

extern uint8_t LowPLC_Interp_Low_tag_int_add_u8;

extern uint8_t LowPLC_Interp_Low_tag_int_sub_u8;

extern uint8_t LowPLC_Interp_Low_tag_int_mul_u8;

extern uint8_t LowPLC_Interp_Low_tag_copy_int_u8;

extern uint8_t LowPLC_Interp_Low_tag_cmp_eq_u8;

extern uint8_t LowPLC_Interp_Low_tag_cmp_ne_u8;

extern uint8_t LowPLC_Interp_Low_tag_cmp_lt_u8;

extern uint8_t LowPLC_Interp_Low_tag_cmp_gt_u8;

extern uint8_t LowPLC_Interp_Low_tag_cmp_le_u8;

extern uint8_t LowPLC_Interp_Low_tag_cmp_ge_u8;

extern uint8_t LowPLC_Interp_Low_tag_if_block_u8;

extern uint8_t LowPLC_Interp_Low_tag_for_block_u8;

extern uint8_t LowPLC_Interp_Low_tag_ton_call_u8;

extern uint8_t LowPLC_Interp_Low_tag_tof_call_u8;

extern uint8_t LowPLC_Interp_Low_tag_tp_call_u8;

extern uint8_t LowPLC_Interp_Low_tag_ctu_call_u8;

extern uint8_t LowPLC_Interp_Low_tag_ctd_call_u8;

extern uint8_t LowPLC_Interp_Low_tag_ctud_call_u8;

extern uint8_t LowPLC_Interp_Low_tag_sr_call_u8;

extern uint8_t LowPLC_Interp_Low_tag_rs_call_u8;

extern uint8_t LowPLC_Interp_Low_tag_rtrig_call_u8;

extern uint8_t LowPLC_Interp_Low_tag_ftrig_call_u8;

uint32_t LowPLC_Interp_Low_pt_us_to_ticks_low(uint32_t pt_us, uint32_t scan_period_us);

void
LowPLC_Interp_Low_exec_simple_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t off,
  uint8_t tag,
  uint16_t len,
  LowPLC_Interp_Low_low_pool p
);

uint8_t LowPLC_Interp_Low_get_sr_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx);

void LowPLC_Interp_Low_set_sr_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx, uint8_t v);

uint8_t LowPLC_Interp_Low_get_rs_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx);

void LowPLC_Interp_Low_set_rs_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx, uint8_t v);

uint8_t LowPLC_Interp_Low_get_rtrig_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx);

void
LowPLC_Interp_Low_set_rtrig_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx, uint8_t v);

uint8_t LowPLC_Interp_Low_get_ftrig_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx);

void
LowPLC_Interp_Low_set_ftrig_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx, uint8_t v);

LowPLC_Interp_Low_ctu_flat
LowPLC_Interp_Low_get_ctu_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx);

void
LowPLC_Interp_Low_set_ctu_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_ctu_flat v
);

LowPLC_Interp_Low_ctd_flat
LowPLC_Interp_Low_get_ctd_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx);

void
LowPLC_Interp_Low_set_ctd_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_ctd_flat v
);

LowPLC_Interp_Low_ctud_flat
LowPLC_Interp_Low_get_ctud_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx);

void
LowPLC_Interp_Low_set_ctud_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_ctud_flat v
);

LowPLC_Interp_Low_ton_flat
LowPLC_Interp_Low_get_ton_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx);

void
LowPLC_Interp_Low_set_ton_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_ton_flat v
);

LowPLC_Interp_Low_tof_flat
LowPLC_Interp_Low_get_tof_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx);

void
LowPLC_Interp_Low_set_tof_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_tof_flat v
);

LowPLC_Interp_Low_tp_flat
LowPLC_Interp_Low_get_tp_state_low(LowPLC_Interp_Low_low_pool p, uint32_t idx);

void
LowPLC_Interp_Low_set_tp_state_low(
  LowPLC_Interp_Low_low_pool p,
  uint32_t idx,
  LowPLC_Interp_Low_tp_flat v
);

void
LowPLC_Interp_Low_exec_fb_call_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t off,
  uint8_t tag,
  uint16_t len,
  LowPLC_Interp_Low_low_pool p
);

void
LowPLC_Interp_Low_exec_stmts_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t off,
  uint32_t rem,
  LowPLC_Interp_Low_low_pool p,
  uint32_t gas
);

void
LowPLC_Interp_Low_exec_if_block_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t poff,
  uint16_t plen,
  LowPLC_Interp_Low_low_pool p,
  uint32_t gas
);

void
LowPLC_Interp_Low_exec_for_block_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t poff,
  uint16_t plen,
  LowPLC_Interp_Low_low_pool p,
  uint32_t gas
);

void
LowPLC_Interp_Low_exec_for_iter_low(
  uint8_t *code,
  uint32_t code_len,
  uint32_t body_off,
  uint32_t body_len,
  uint32_t idx_i,
  int16_t end_v,
  LowPLC_Interp_Low_low_pool p,
  uint32_t iters_left,
  uint32_t gas
);


#define LowPLC_Interp_Low_H_DEFINED
#endif /* LowPLC_Interp_Low_H */
